
POST http://localhost:8080/address
Content-Type: application/json

{
  "country": "Russian Federation",
  "city": "Zvenigovo",
  "streetName": "Puskhino",
  "buildingNumber": 54,
  "flatNumber": 9,
  "zipCode": "425060",
  "addressType": "FLAT"
}

###
GET http://localhost:8080/address

###
GET http://localhost:8080/address

###
DELETE http://localhost:8080/address/5

###
PUT http://localhost:8080/address
Content-Type: application/json

{
  "id": 1,
  "country": "USA",
  "city": "Texas",
  "streetName": "Lenina street",
  "buildingNumber": 1,
  "flatNumber": 1,
  "zipCode": "000123",
  "addressType": "FLAT"
}